name: Test private message

on:
  issues:
    types: 
      - opened

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v1
      - uses: daniL16/action-notify-rocketChat@2.0.1
        with:
          message: 'Test'
          ROCKET_CHAT_USER: ${{ secrets.ROCKET_CHAT_USER }}
          ROCKET_CHAT_PASS: ${{ secrets.ROCKET_CHAT_PASS }}
          ROCKET_CHAT_URL: ${{ secrets.ROCKET_CHAT_HOST }}
          MESSAGE_TO: obrian
          BOT_NAME: 'Pingu'
          BOT_AVATAR: 'https://i.pinimg.com/originals/bd/5c/46/bd5c46c4c1579c56c60920301ea3e642.png'
