name: Notify Hitobito Office

on:
  issues:
    types: 
      - opened
  pull_request:
    types:
      -opened

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: Notify-Hitobito
    env:
       ISSUE_URL: ${{ github.event.issue.html_url }}
       ISSUE_TITLE: ${{ github.event.issue.title }}
       ISSUE_NUMBER: ${{ github.event.issue.number }}
       ACTOR_URL: ${{ github.event.issue.actor.html_url }}
       ACTOR_NAME: ${{ github.event.issue.actor.login }}
       ACTOR_AVATAR: ${{ github.event.issue.actor.avatar_url }}
    #   MESSAGE: "New Issue/PR: $ISSUE_NUMBER - $ISSUE_TITLE - $ISSUE_URL"
    steps:
      - uses: actions/checkout@v1
      - uses: daniL16/action-notify-rocketChat@2.0.1
        with:
          message: 'New Issue $ISSUE_NUMBER - $ISSUE_TITLE - $ISSUE_URL'
          ROCKET_CHAT_HOOK: ${{ secrets.ROCKET_CHAT_HOOK }}
          ROCKET_CHAT_URL: ${{ secrets.ROCKET_CHAT_HOST }}
          BOT_NAME: 'Hitbotor'
          BOT_AVATAR: 'https://media.metrolatam.com/2019/10/16/18ps27-638137169a2d73f9f63481c115a7f092.jpg'
          # BOT_NAME: $ACTOR_NAME
          # BOT_AVATAR: $ACTOR_AVATAR
      - run: echo "Message New Issue/PR $ISSUE_NUMBER - $ISSUE_TITLE - $ISSUE_URL"
