name: Notify Hitobito Office
uses: daniL16/action-notify-rocketChat@2.0.1

on:
  issues:
    types: 
      - opened
  pull_request:
    types:
      -opened

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          message: ${{ github.event.pull_request.html_url }}
          ROCKET_CHAT_HOOK: ${{ secrets.ROCKET_CHAT_HOOK }}
          ROCKET_CHAT_URL: ${{ secrets.ROCKET_CHAT_HOST }}
          BOT_NAME: 'Hitnina'
          BOT_AVATAR: 'https://media.metrolatam.com/2019/10/16/18ps27-638137169a2d73f9f63481c115a7f092.jpg'
