name: Translate Markdown

on:
  push:
    branches:
      - main
    paths:
      - 'README.md' # Pfad zu deiner Quelldatei

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Wichtig für die Commit-Rechte

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: DeepL Translate
        uses: lyqht/deepl-translate-github-action@v2.1.0
        with:
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
          input_file_path: 'README.md'
          output_file_name_pattern: 'README.en.md'
          target_languages: 'en-GB'

      - name: Commit translated file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto-translate README [skip ci]"
